import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, BookOpen, ChevronRight, Search, RefreshCw, X, Layers, Globe, AlertCircle, MoreVertical, Check } from 'lucide-react';
import { DUA_LANGUAGES, loadDuaDataset } from '../lib/duaCdn';
import type { CdnDua, CdnChapter, DuaLanguage, DuaDatasetResult } from '../lib/duaCdn';

const IA_DUAS: { c: string; ar: string; ur: string }[] = [
  {c:"صبح اٹھ کر پڑھنے کی دعا",ar:"أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ",ur:"ہم نے صبح کی اور سارا ملک اللہ ہی کا ہے، اور سب تعریف اللہ کے لیے ہے۔"},
  {c:"رات کو سونے کی دعا",ar:"بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",ur:"اے اللہ! تیرے نام کے ساتھ میں مرتا ہوں اور جیتا ہوں۔"},
  {c:"کھانا شروع کرنے کی دعا",ar:"بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",ur:"میں اللہ کے نام سے اور اللہ کی برکت کے ساتھ کھانا شروع کرتا ہوں۔"},
  {c:"کھانے کے بعد کی دعا",ar:"الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",ur:"سب تعریفیں اللہ ہی کے لیے ہیں جس نے ہمیں کھلایا پلایا اور مسلمان بنایا۔"},
  {c:"گھر سے نکلتے وقت کی دعا",ar:"بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",ur:"اللہ کے نام کے ساتھ، میں نے اللہ پر توکل کیا، ہر طاقت اللہ ہی سے ہے۔"},
  {c:"گھر میں داخل ہوتے وقت کی دعا",ar:"اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ",ur:"اے اللہ! میں تجھ سے گھر داخل ہونے اور باہر نکلنے کی بھلائی کا طالب ہوں۔"},
  {c:"مسجد میں داخل ہونے کی دعا",ar:"اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",ur:"اے اللہ! میرے لیے اپنی رحمت کے دروازے کھول دے۔"},
  {c:"مسجد سے نکلتے وقت کی دعا",ar:"اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",ur:"اے اللہ! میں تجھ سے تیرے فضل کا سوال کرتا ہوں۔"},
  {c:"استغفار کی جامع دعا",ar:"أَسْتَغْفِرُ اللَّهَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",ur:"میں اس اللہ سے معافی مانگتا ہوں جس کے سوا کوئی معبود نہیں، جو ہمیشہ زندہ اور قائم ہے اور اسی کی طرف رجوع کرتا ہوں۔"},
  {c:"پریشانی اور مصیبت کی دعا",ar:"لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",ur:"تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ہی قصوروار تھا۔"}
];

const PAGE_SIZE = 16;
const normalize = (s: string) => s.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f\u064B-\u065F\u0670]/g, '');
function BrandLoader() {
  return <div className="dv-loader" role="status" aria-live="polite"><div className="dv-brand-word" aria-hidden="true">{'StepTuDeen'.split('').map((letter, i) => <span key={i} style={{ animationDelay: `${i * .075}s` }}>{letter}</span>)}</div><div className="dv-loader-track" aria-hidden="true"><span/></div><p>StepTuDeen — Loading duas…</p></div>;
}
function TranslationWarning({ language, onClose }: { language: DuaLanguage; onClose: () => void }) {
  return <div className="dv-modal-back" onClick={onClose}>
    <div className="dv-modal" role="alertdialog" aria-modal="true" aria-labelledby="dv-modal-title" onClick={e => e.stopPropagation()}>
      <strong id="dv-modal-title">Machine translation</strong>
      <p>This translation was generated by a machine and has not been reviewed by a person. Please check it against a trusted published translation.</p>
      {language === 'ur' && <p className="font-urdu" dir="rtl">یہ مشینی ترجمہ ہے، اس کی انسانی نظرِ ثانی نہیں ہوئی۔ مستند مطبوعہ ترجمے سے تصدیق کریں۔</p>}
      {language === 'hi' && <p lang="hi">यह मशीनी अनुवाद है, जिसकी मानव समीक्षा नहीं हुई है। प्रामाणिक प्रकाशित अनुवाद से सत्यापन करें।</p>}
      <button className="dv-btn" autoFocus onClick={onClose}>OK</button>
    </div>
  </div>;
}
function DuaReader({ dua, chapter, language, transliteration }: { dua: CdnDua; chapter: CdnChapter; language: DuaLanguage; transliteration: boolean }) {
  const chosen = DUA_LANGUAGES.find(l => l.code === language)!;
  const reference = dua.reference;
  return <article className="dv-card dv-reader">
    <header className="dv-reader-heading"><div className="dv-row dv-spread"><span className="dv-pill">Entry {reference?.sourceReference || dua.id}</span>{dua.repeat && dua.repeat > 1 ? <span className="dv-pill">Repeat {dua.repeat} times</span> : null}</div><h2>{dua.title}</h2><p className={`dv-muted ${chosen.dir === 'rtl' ? 'font-urdu' : ''}`} dir={chosen.dir}>{chapter.title}</p></header>
    <p className="dv-arabic font-amiri" dir="rtl" lang="ar">{dua.arabic}</p>
    {transliteration && dua.transliteration && <div className="dv-text-block"><span className="dv-label">Transliteration</span><p className="dv-transliteration">{dua.transliteration}</p></div>}
    {language !== 'ar' && <div className="dv-text-block"><span className="dv-label">{chosen.name} · {dua.translationKind === 'machine' ? 'Machine translation' : 'Translation'}</span><p className={language === 'ur' ? 'font-urdu' : ''} lang={language} dir={chosen.dir}>{dua.text}</p></div>}
    {dua.guidance && <p className="dv-note">{dua.guidance}</p>}
    {dua.placeholders?.length ? <div className="dv-note"><span className="dv-label">Note</span>{Array.from(new Map(dua.placeholders.map(p => [p.key, p])).values()).map(p => <p key={p.key}><code>{`{{${p.key}}}`}</code> — {p.instruction}</p>)}</div> : null}
    {dua.parts?.length ? <details><summary>More parts ({dua.parts.length})</summary>{dua.parts.map((part, i) => <section className="dv-part" key={i}><span className="dv-pill">Part {i + 1}{part.times && part.times > 1 ? ` · ${part.times} times` : ''}</span><p className="dv-arabic font-amiri" dir="rtl" lang="ar">{part.arabic}</p>{transliteration && part.transliteration && <p className="dv-transliteration dv-context">{part.transliteration}</p>}{part.en && <div className="dv-text-block"><span className="dv-label">Meaning (English)</span><p lang="en" dir="ltr">{part.en}</p></div>}</section>)}</details> : null}
    <div className="dv-references"><span className="dv-label">Reference</span><p>Hisn al-Muslim · {reference?.sourceReference || dua.id}</p>{reference?.references?.map((ref, i) => <p key={i}>{ref.reference}{ref.grades?.map((grade, n) => <span key={n}> · {grade.value}{grade.gradedBy ? ` (${grade.gradedBy})` : ''}</span>)}</p>)}</div>
  </article>;
}
export const DuasView: React.FC = () => {
  const [language, setLanguage] = useState<DuaLanguage>('ar');
  const [source, setSource] = useState<'cdn' | 'local'>('cdn');
  const [mode, setMode] = useState<'chapters' | 'entries'>('chapters');
  const [chapterId, setChapterId] = useState<number | null>(null);
  const [entryId, setEntryId] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(1);
  const [refresh, setRefresh] = useState(0);
  const [transliteration, setTransliteration] = useState(true);
  const [menuOpen, setMenuOpen] = useState(false);
  const [notice, setNotice] = useState<DuaLanguage | null>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!menuOpen) return;
    const close = (e: MouseEvent | TouchEvent) => { if (menuRef.current && !menuRef.current.contains(e.target as Node)) setMenuOpen(false); };
    const esc = (e: KeyboardEvent) => { if (e.key === 'Escape') setMenuOpen(false); };
    document.addEventListener('mousedown', close); document.addEventListener('touchstart', close); document.addEventListener('keydown', esc);
    return () => { document.removeEventListener('mousedown', close); document.removeEventListener('touchstart', close); document.removeEventListener('keydown', esc); };
  }, [menuOpen]);
  const [state, setState] = useState<{ result: DuaDatasetResult | null; loading: boolean; error: string }>({ result: null, loading: true, error: '' });
  useEffect(() => {
    const controller = new AbortController();
    setState({ result: null, loading: true, error: '' });
    loadDuaDataset(language, controller.signal, refresh > 0).then(result => {
      if (!controller.signal.aborted) setState({ result, loading: false, error: '' });
    }).catch(error => {
      if (!controller.signal.aborted) setState({ result: null, loading: false, error: error instanceof Error ? error.message : 'Could not load the library.' });
    });
    return () => controller.abort();
  }, [language, refresh]);
  const result = state.result?.data.meta.language === language ? state.result : null;
  const data = result?.data;
  const chapters = data?.chapters || [];
  const currentChapter = chapters.find(c => c.id === chapterId);
  const allEntries = useMemo(() => chapters.flatMap(chapter => chapter.duas.map(dua => ({ dua, chapter }))), [data]);
  const selected = allEntries.find(item => item.dua.id === entryId);
  const search = normalize(query.trim());
  const isChapters = mode === 'chapters' && chapterId === null;
  const filteredChapters = chapters.filter(c => normalize(`${c.id} ${c.title} ${c.titleArabic} ${c.tags.join(' ')} ${c.duas.map(d => `${d.title} ${d.arabic} ${d.text} ${d.transliteration || ''}`).join(' ')}`).includes(search));
  const filteredEntries = allEntries.filter(({dua, chapter}) => (chapterId === null || chapter.id === chapterId) && normalize(`${dua.id} ${dua.reference?.sourceReference || ''} ${dua.title} ${chapter.title} ${dua.arabic} ${dua.text} ${dua.transliteration || ''}`).includes(search));
  const count = isChapters ? filteredChapters.length : filteredEntries.length;
  const pages = Math.max(1, Math.ceil(count / PAGE_SIZE));
  const safePage = Math.min(page, pages);
  const start = (safePage - 1) * PAGE_SIZE;
  const local = IA_DUAS.filter(dua => normalize(`${dua.c} ${dua.ar} ${dua.ur}`).includes(search));
  const reset = () => { setQuery(''); setPage(1); };
  const chooseSource = (next: 'cdn' | 'local') => {setSource(next);setEntryId(null);setChapterId(null);reset();};
  const chosen = DUA_LANGUAGES.find(l => l.code === language)!;
  const back = () => { if (entryId) setEntryId(null); else { setChapterId(null); reset(); } };
  return <main className="dv" dir="ltr">
    <style>{`
      .dv{--dv-blue:#75b5ff;--dv-ink:#080808;min-height:100vh;background:#fff;color:var(--dv-ink);padding:22px 16px 90px;font-family:inherit;box-sizing:border-box}
      .dv *{box-sizing:border-box}.dv button,.dv input{font:inherit}.dv button{cursor:pointer}.dv h1,.dv h2,.dv h3,.dv p{margin:0}.dv .dv-shell{max-width:980px;margin:auto}
      .dv .dv-card{background:#fff;border:1px solid #0000000e;border-radius:22px;box-shadow:0 12px 30px #00000008,0 3px 7px #00000006}
      .dv .dv-hero{border-top:3px solid var(--dv-blue);padding:26px 22px;margin-bottom:22px}.dv .dv-row{display:flex;align-items:center;gap:10px}.dv .dv-spread{justify-content:space-between;flex-wrap:wrap}.dv .dv-icon{display:grid;place-items:center;width:46px;height:46px;border-radius:15px;background:var(--dv-blue);flex-shrink:0}
      .dv .dv-kicker{font-size:10px;font-weight:800;letter-spacing:.18em;opacity:.55;margin-bottom:6px}.dv h1{font-size:29px;font-weight:800;letter-spacing:-.035em;line-height:1.4}.dv .dv-hero-description{font-size:13px;opacity:.65;line-height:1.9;margin-top:12px}.dv .dv-stats{display:flex;gap:20px;border-top:1px solid #0000000c;margin-top:20px;padding-top:18px}.dv .dv-stats strong{font-size:23px;letter-spacing:-.04em;display:block}.dv .dv-stats span{font-size:10px;opacity:.55}
      .dv .dv-btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;background:var(--dv-blue);color:#000;border:1px solid #00000010;border-radius:12px;padding:10px 14px;min-height:42px;font-size:12px;font-weight:700;box-shadow:0 3px 0 #00000010;transition:background .15s,box-shadow .15s}.dv .dv-btn:hover{background:#96c7ff;box-shadow:0 5px 12px #00000012}.dv button:focus-visible,.dv input:focus-visible{outline:3px solid #1680ef;outline-offset:3px}.dv .dv-btn:disabled{opacity:.4;cursor:not-allowed}
      .dv .dv-tabs{display:flex;gap:10px;margin-bottom:18px}.dv .dv-tabs .dv-btn{flex:1;background:#d9eaff;box-shadow:none}.dv .dv-tabs .dv-active{background:var(--dv-blue);box-shadow:0 3px 0 #00000015;border-color:#3284de}
      .dv .dv-toolbar{display:flex;align-items:center;gap:10px;margin-bottom:18px;flex-wrap:wrap}.dv .dv-search{display:flex;align-items:center;gap:10px;border:1px solid #00000018;box-shadow:0 3px 10px #00000004;border-radius:14px;padding:7px 12px;flex:1;min-width:180px;min-height:46px}.dv .dv-search input{background:#fff;color:#000;border:0;width:100%;min-width:0;font-size:12px;padding:5px 0;outline:none}.dv .dv-clear{background:var(--dv-blue);border:0;border-radius:8px;display:grid;place-items:center;min-width:30px;min-height:30px;color:#000}
      .dv .dv-section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:20px 0 14px}.dv .dv-section-head h2{font-size:15px;font-weight:800}.dv .dv-count{font-size:11px;padding:6px 9px;border:1px solid #00000015;border-radius:8px}.dv .dv-catalogue{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}
      .dv .dv-catalogue-card{padding:18px;text-align:left;display:flex;flex-direction:column;gap:13px;transition:box-shadow .2s;color:#000;width:100%}.dv .dv-catalogue-card:hover{box-shadow:0 14px 30px #00000010;border-color:#75b5ff}.dv .dv-catalogue-card h3{font-size:13px;font-weight:700;line-height:1.65;overflow-wrap:anywhere}.dv .dv-catalogue-card .dv-open{display:inline-flex;align-items:center;gap:6px;background:var(--dv-blue);color:#000;font-size:10px;font-weight:700;border-radius:8px;padding:6px 9px}.dv .dv-card-number{font-size:10px;opacity:.5;font-weight:700}.dv .dv-card-bottom{margin-top:auto}
      .dv .dv-muted{font-size:11px;opacity:.58;line-height:1.7}.dv .dv-note{font-size:12px;line-height:1.8;padding:12px 14px;border:1px solid #bcd9fc;border-inline-start:3px solid var(--dv-blue);border-radius:10px;margin:12px 0!important}.dv .dv-cache{font-size:10px;opacity:.6;margin:10px 0 16px;line-height:1.7}.dv .dv-pagination{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:22px}.dv .dv-pagination span{font-size:11px;opacity:.65}
      .dv .dv-reader{padding:24px 20px}.dv .dv-reader-heading{border-bottom:1px solid #0000000d;padding-bottom:19px;margin-bottom:20px}.dv .dv-reader-heading h2{font-size:20px;line-height:1.6;font-weight:800;margin:12px 0 8px;letter-spacing:-.025em}.dv .dv-pill{display:inline-flex;font-size:10px;font-weight:700;padding:6px 10px;border:1px solid #00000018;border-radius:8px}.dv .dv-label{display:block;font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;opacity:.5;margin-bottom:6px}.dv .dv-steps{display:grid;gap:20px}.dv .dv-step+.dv-step{border-top:1px solid #00000010;padding-top:20px}.dv .dv-dua-text+.dv-dua-text{border-top:1px solid #00000010;margin-top:22px;padding-top:22px}.dv .dv-arabic{font-size:clamp(30px,6vw,38px);line-height:2.2;text-align:right;color:#000;margin:18px 0 24px;overflow-wrap:anywhere}.dv .dv-text-block{border-top:1px solid #0000000a;padding-top:15px;margin-top:15px}.dv .dv-text-block p,.dv .dv-context{font-size:14px;line-height:1.95;overflow-wrap:anywhere}.dv .dv-context{margin-top:12px}.dv .dv-transliteration{font-style:italic;opacity:.72}.dv .dv-variation+.dv-variation{border-top:2px solid #75b5ff;margin-top:24px;padding-top:22px}.dv .dv-variation h3{font-size:14px;margin-bottom:14px}.dv .dv-repeat{border-inline-start:3px solid #75b5ff;padding-inline-start:15px}.dv .dv-repeat>.dv-pill{margin-bottom:14px}.dv .dv-references{border-top:1px solid #00000012;margin-top:18px;padding-top:14px}.dv .dv-references p{font-size:11px;line-height:1.85}.dv .dv-local{display:grid;gap:18px}.dv .dv-local h3{font-size:15px;line-height:1.9}.dv .dv-local .dv-urdu{font-size:14px;line-height:2.2;text-align:right;border-top:1px solid #00000010;padding-top:15px}
      .dv .dv-loader{padding:56px 12px;text-align:center}.dv .dv-brand-word{display:flex;justify-content:center;font-size:29px;font-weight:800;letter-spacing:-.03em}.dv .dv-brand-word span{display:inline-block;animation:dv-brand-wave 1.35s ease-in-out infinite}.dv .dv-loader p{font-size:11px;opacity:.55;margin-top:17px}.dv .dv-loader-track{width:100px;height:3px;background:#0000000b;border-radius:10px;overflow:hidden;margin:16px auto 0}.dv .dv-loader-track span{display:block;width:40%;height:100%;background:var(--dv-blue);animation:dv-loader-slide 1.4s ease-in-out infinite}.dv .dv-empty{display:flex;flex-direction:column;align-items:center;gap:14px;padding:38px 20px;text-align:center}.dv .dv-empty h3{font-size:14px}.dv .dv-empty p{font-size:12px;line-height:1.8;opacity:.65}.dv .dv-footer{border-top:1px solid #0000000c;padding-top:20px;margin-top:30px;font-size:10px;line-height:1.9;opacity:.65}.dv .dv-footer a{color:#000;text-decoration:underline;text-underline-offset:3px}
      .dv .dv-language{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:16px 0}.dv .dv-language label{font-size:12px;font-weight:700}.dv .dv-language select{background:#75b5ff;color:#000;border:1px solid #00000018;border-radius:12px;min-height:44px;padding:8px 12px;font:inherit;font-size:13px;max-width:100%;flex:1}.dv .dv-machine{border:1px solid #00000018;border-inline-start:4px solid #75b5ff;padding:15px;border-radius:14px;font-size:12px;line-height:1.9;margin:16px 0;background:#fff}.dv .dv-machine strong{display:block;margin-bottom:5px}.dv details{margin-top:20px;border-top:1px solid #00000012;padding-top:14px}.dv summary{cursor:pointer;font-size:12px;font-weight:700;line-height:1.8}.dv .dv-part{border:1px solid #00000012;border-radius:14px;padding:15px;margin-top:14px}.dv select:focus-visible,.dv summary:focus-visible{outline:3px solid #1680ef;outline-offset:3px}.dv .dv-card-bottom{gap:8px}
      .dv .dv-menu-wrap{position:relative;flex-shrink:0}.dv .dv-menu-btn{width:46px;height:46px;border-radius:14px;border:1px solid #00000018;background:#fff;color:#000;display:grid;place-items:center;box-shadow:0 3px 10px #00000004}.dv .dv-menu-btn[aria-expanded=true]{background:#d9eaff;border-color:#3284de}.dv .dv-menu{position:absolute;right:0;top:calc(100% + 8px);z-index:30;min-width:230px;max-height:70vh;overflow:auto;background:#fff;border:1px solid #0000001a;border-radius:16px;box-shadow:0 16px 36px #00000018;padding:8px}.dv .dv-menu-title{display:flex;align-items:center;gap:7px;font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;opacity:.55;padding:8px 10px 6px}.dv .dv-menu-item{width:100%;display:flex;align-items:center;justify-content:space-between;gap:10px;background:transparent;border:0;border-radius:10px;padding:10px;font-size:13px;color:#000;text-align:left}.dv .dv-menu-item:hover{background:#eef6ff}.dv .dv-menu-item[aria-checked=true]{background:#d9eaff;font-weight:700}.dv .dv-menu-sep{height:1px;background:#0000000f;margin:6px 4px}.dv .dv-toolbar{flex-wrap:nowrap}.dv .dv-toolbar .dv-back{flex-shrink:0;padding:0;width:46px;min-height:46px}.dv .dv-toolbar .dv-search{min-width:0}
.dv .dv-modal-back{position:fixed;inset:0;z-index:100;background:#0000006b;display:grid;place-items:center;padding:20px}.dv .dv-modal{background:#fff;border-radius:20px;max-width:380px;width:100%;padding:24px 22px;box-shadow:0 24px 60px #00000040;display:grid;gap:12px}.dv .dv-modal strong{font-size:16px}.dv .dv-modal p{font-size:13px;line-height:1.9}.dv .dv-modal .dv-btn{justify-self:end;min-width:90px;margin-top:6px}
      @keyframes dv-brand-wave{0%,65%,100%{transform:translateY(0);color:#080808}30%{transform:translateY(-7px);color:#1680ef}}@keyframes dv-loader-slide{0%{transform:translateX(-100%)}100%{transform:translateX(350%)}}
      @media(min-width:700px){.dv{padding:30px 24px 90px}.dv .dv-catalogue{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:360px){.dv .dv-catalogue{grid-template-columns:1fr}.dv .dv-stats{gap:15px}.dv .dv-btn{padding:9px 11px}}@media(prefers-reduced-motion:reduce){.dv .dv-brand-word span,.dv .dv-loader-track span{animation:none}.dv *{transition:none!important}}
    `}</style>
    <div className="dv-shell">
      <div className="dv-toolbar">
        {source === 'cdn' && (chapterId !== null || entryId) && <button className="dv-btn dv-back" aria-label={entryId ? 'Back to entries' : 'All chapters'} onClick={back}><ArrowLeft size={16}/></button>}
        {!entryId ? <label className="dv-search"><Search size={17} aria-hidden="true"/><input aria-label="Search duas" value={query} placeholder="Search titles, Arabic or translation…" onChange={event => {setQuery(event.target.value);setPage(1);}}/>{query && <button className="dv-clear" aria-label="Clear search" onClick={reset}><X size={14}/></button>}</label> : <div style={{flex:1}}>{<button className="dv-btn" aria-pressed={transliteration} onClick={() => setTransliteration(v => !v)}>{transliteration ? 'Hide' : 'Show'} transliteration</button>}</div>}
        <div className="dv-menu-wrap" ref={menuRef}>
          <button className="dv-menu-btn" aria-label="Menu" aria-haspopup="menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(v => !v)}><MoreVertical size={20}/></button>
          {menuOpen && <div className="dv-menu" role="menu">
            <div className="dv-menu-title"><Globe size={13}/> Language</div>
            {DUA_LANGUAGES.map(item => <button key={item.code} role="menuitemradio" aria-checked={source === 'cdn' && language === item.code} className="dv-menu-item" onClick={() => {if (source !== 'cdn') chooseSource('cdn'); if (item.code !== language) {setLanguage(item.code as DuaLanguage);setRefresh(0);reset();if (item.code === 'ur' || item.code === 'hi') setNotice(item.code as DuaLanguage);} setMenuOpen(false);}}><span>{item.label}</span>{source === 'cdn' && language === item.code && <Check size={15}/>}</button>)}
            <div className="dv-menu-sep"/>
            <button role="menuitemradio" aria-checked={source === 'local'} className="dv-menu-item font-urdu" onClick={() => {chooseSource(source === 'local' ? 'cdn' : 'local');setMenuOpen(false);}}><span>پہلے سے موجود اردو</span>{source === 'local' && <Check size={15}/>}</button>
            {source === 'cdn' && <button role="menuitem" className="dv-menu-item" disabled={state.loading} onClick={() => {setRefresh(n => n + 1);setMenuOpen(false);}}><span>Refresh</span><RefreshCw size={14}/></button>}
          </div>}
        </div>
      </div>
      {notice && <TranslationWarning language={notice} onClose={() => setNotice(null)}/>}
      {source === 'local' ? <><div className="dv-local">{local.map((dua, i) => <article className="dv-card dv-reader" key={dua.c}><div className="dv-row dv-spread"><span className="dv-card-number">DUA {i + 1}</span><h3 className="font-urdu" dir="rtl">{dua.c}</h3></div><p className="dv-arabic font-amiri" dir="rtl" lang="ar">{dua.ar}</p><p className="dv-urdu font-urdu" dir="rtl" lang="ur">{dua.ur}</p></article>)}</div>{!local.length && <p className="dv-note">No matching duas.</p>}</> : state.loading || (!result && !state.error) ? <BrandLoader/> : state.error ? <div className="dv-card dv-empty" role="alert"><AlertCircle size={25}/><h3>Couldn't load the duas</h3><p>Please check your internet connection and try again.</p><button className="dv-btn" onClick={() => setRefresh(n => n + 1)}><RefreshCw size={15}/> Try again</button><p className="font-urdu" dir="rtl">انٹرنیٹ چیک کر کے دوبارہ کوشش کریں۔ مینیو سے "پہلے سے موجود اردو" دعائیں بھی پڑھی جا سکتی ہیں۔</p></div> : <>
        {selected ? <DuaReader dua={selected.dua} chapter={selected.chapter} language={language} transliteration={transliteration}/> : entryId ? <div className="dv-card dv-empty"><h3>This entry is not available in this language.</h3><button className="dv-btn" onClick={() => setEntryId(null)}>Back</button></div> : <>
          {chapterId === null && <div className="dv-tabs" aria-label="Browse mode"><button className={`dv-btn ${mode === 'chapters' ? 'dv-active' : ''}`} aria-pressed={mode === 'chapters'} onClick={() => {setMode('chapters');reset();}}><Layers size={14}/> Chapters</button><button className={`dv-btn ${mode === 'entries' ? 'dv-active' : ''}`} aria-pressed={mode === 'entries'} onClick={() => {setMode('entries');reset();}}>All entries <ArrowUpRight size={14}/></button></div>}
          <div className="dv-section-head"><h2 dir={currentChapter ? chosen.dir : 'ltr'}>{currentChapter?.title || (isChapters ? 'Find a moment. Find a dua.' : 'All entries')}</h2><span className="dv-count">{count}</span></div>
          {!count ? <div className="dv-card dv-empty"><Search size={25}/><h3>No matching results</h3><p>Try an Arabic word, translation, title or reference number.</p><button className="dv-btn" onClick={reset}>Clear search</button></div> : <div className="dv-catalogue">{isChapters ? filteredChapters.slice(start, start + PAGE_SIZE).map(chapter => <button className="dv-card dv-catalogue-card" key={chapter.id} onClick={() => {setChapterId(chapter.id);reset();}}><div className="dv-row dv-spread"><span className="dv-card-number">CHAPTER {chapter.id}</span><BookOpen size={15}/></div><h3 className={chosen.dir === 'rtl' ? 'font-urdu' : ''} dir={chosen.dir}>{chapter.title}</h3><div className="dv-row dv-spread dv-card-bottom"><span className="dv-muted">{chapter.duas.length} entries</span><span className="dv-open">Open <ChevronRight size={12}/></span></div></button>) : filteredEntries.slice(start, start + PAGE_SIZE).map(({dua, chapter}) => <button className="dv-card dv-catalogue-card" key={dua.id} onClick={() => setEntryId(dua.id)}><div className="dv-row dv-spread"><span className="dv-card-number">ENTRY {dua.reference?.sourceReference || dua.id}</span><BookOpen size={15}/></div><h3>{dua.title}</h3><p className={`dv-muted ${chosen.dir === 'rtl' ? 'font-urdu' : ''}`} dir={chosen.dir}>{chapter.title}</p><div className="dv-row dv-spread dv-card-bottom"><span className="dv-muted">{dua.id}</span><span className="dv-open">Read <ChevronRight size={12}/></span></div></button>)}</div>}
          {pages > 1 && <nav className="dv-pagination" aria-label="Library pages"><button className="dv-btn" disabled={safePage === 1} onClick={() => setPage(safePage - 1)}><ArrowLeft size={14}/> Previous</button><span>{safePage} / {pages}</span><button className="dv-btn" disabled={safePage === pages} onClick={() => setPage(safePage + 1)}>Next <ChevronRight size={14}/></button></nav>}
        </>}
      </>}
    </div>
  </main>;
};
export default DuasView;
